"""update key model

Revision ID: 8a80d8f291eb
Revises: b4968e8fda3d
Create Date: 2022-02-03 13:15:33.702554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8a80d8f291eb"
down_revision = "b4968e8fda3d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("keys", "user", existing_type=sa.BIGINT(), nullable=False)
    op.drop_constraint("fk_keys_users_id_user", "keys", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key("fk_keys_users_id_user", "keys", "users", ["user"], ["id"])
    op.alter_column("keys", "user", existing_type=sa.BIGINT(), nullable=True)
    # ### end Alembic commands ###
